### ISSUE TITLE
RouteDataAssertions is not compatible with the latest version of FluentAssertions

### ISSUE THREAD

**Issue by rikrak** [CaseyBurns/FluentAssertions.MVC#24]
Hi,

My project uses nuget package 0.5.0.0 of FluentAssertions.MVC5.  I've just upgraded to v3.3.0 of FluentAssertions and I notice there are some breaking changes in Fluent Assertions.

When running a test that uses the RouteDataAssertions:

routeData.Should()
    .HaveController("Customer")
    .HaveAction("Edit")
    .HaveValue("Id", 123);

I receive the following MissingMethodException:
System.MissingMethodException: Method not found: 'Boolean FluentAssertions.Execution.AssertionScope.FailWith(System.String, System.Object[])'.

Looks like Fluent Assertions has changed the signature to this method to be:

public Continuation FailWith(string message, params object[] args)

(ref: https://github.com/dennisdoomen/fluentassertions/commit/2cf13d4db65b1867f6b3e4e950edc049d6a2d11a)
Rik

**Comment by kevinkuszyk** [comment]
I just pushed version `0.6.0-beta1` to Nuget which is built against Fluent Assertions v3.3.0.  I think that should fix your issue.  Can you try that version and confirm?  Thanks!

**Comment by rikrak** [comment]
Hi @kevinkuszyk 
The beta package appears to have fixed the issue.  

Thanks!

In what sort of timeframe will this be pushed to live?

Rik

**Comment by kevinkuszyk** [comment]
Version [0.6.0](https://github.com/CaseyBurns/FluentAssertions.MVC/releases/tag/v0.6.0) is up on NuGet now.
